name: Continuos Integration API

on:
  push:
    branches:
      - develop
    paths:
      - api/**
  pull_request:
    branches:
      - master
    paths:
      - api/**

jobs:
  linting:
    name: 'Linting'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.x'
      - run: npm ci
      - run: npm run lint

  testing:
    name: 'Testing'
    runs-on: ubuntu-latest
    needs: linting
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.3.x'
      - run: cp .env.sample .env
      - run: npm ci
      - run: docker-compose up -d pg_aee_test
      - run: npm run test:cov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./api/coverage/lcov.info
          base-path: api

      # - run: sudo chown -R $USER ./.docker

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Build and push
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./api
      #     push: true
      #     tags: luizhsou1/aee:latest


    