name: Continuos Deployment API

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - api/**

jobs:
  build-image:
    name: 'Build Image'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    defaults:
      run:
        working-directory: api
    steps:
      - uses: actions/checkout@v2
        if: github.event.pull_request.merged
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          push: true
          tags: luizhsou1/aee-api:latest

  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    needs: build-image
    defaults:
      run:
        working-directory: api
    steps:
      - name: Update API by SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_EC2_PRD }}
          username: ${{ secrets.SSH_USERNAME_EC2_PRD }}
          key: ${{ secrets.SSH_KEY_EC2_PRD }}
          port: ${{ secrets.SSH_PORT_EC2_PRD }}
          script: |
            docker-compose pull
            docker-compose up -d --force-recreate aee_api