name: Continuos Deployment APP

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - app/**

jobs:
  build-image:
    name: 'Build Image'
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
        if: github.event.pull_request.merged
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./app
          push: true
          tags: luizhsou1/aee-app:latest


    