name: Continuos Integration APP

on:
  push:
    branches:
      - develop
    paths:
      - app/**

jobs:
  linting:
    name: 'Linting'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.19.x'
      - run: npm ci
      - run: npm run lint -- --no-fix
    